"""Pipeline: read eligible X items → extract structured insights → store.

Reads from x_items.sqlite (eligible only), writes to x_insights.sqlite.
Makes no API calls and never modifies x_items.
"""
from __future__ import annotations

import logging
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from integrations.x_api.insight_extractor import extract_insight
from integrations.x_api.insight_models import XInsight, init_db as init_insights_db, insert_insight
from integrations.x_api.models import init_db as init_items_db

logger = logging.getLogger(__name__)

_SI_INBOX = (
    Path(__file__).resolve().parent.parent.parent / "ops" / "self_improvement" / "inbox"
)


def run_insight_extraction(
    items_db_path: Optional[Path] = None,
    insights_db_path: Optional[Path] = None,
    dry_run: bool = True,
    create_si_cards: bool = False,
    limit: int = 500,
) -> dict:
    """Extract insights from eligible x_items and store them.

    Args:
        items_db_path:    Path to x_items.sqlite (None = default)
        insights_db_path: Path to x_insights.sqlite (None = default)
        dry_run:          If True, extract but do not write
        create_si_cards:  If True, write self-improvement card stubs for new insights
        limit:            Max eligible items to process per run

    Returns a summary dict with counts.
    """
    items_conn    = init_items_db(items_db_path)
    insights_conn = init_insights_db(insights_db_path)

    rows = items_conn.execute(
        "SELECT * FROM x_items WHERE processed_status='eligible' "
        "ORDER BY fetched_at DESC LIMIT ?",
        (limit,),
    ).fetchall()
    items_conn.close()

    processed = 0
    created   = 0
    skipped   = 0
    errors: list[str] = []

    for row in rows:
        item = dict(row)
        processed += 1
        try:
            insight = extract_insight(item)
        except Exception as exc:
            errors.append(f"{item.get('x_item_id')}: {exc}")
            skipped += 1
            continue

        if insight is None:
            skipped += 1
            continue

        if not dry_run:
            inserted = insert_insight(insights_conn, insight)
            if inserted:
                created += 1
                if create_si_cards:
                    _maybe_write_si_card(insight)
            else:
                skipped += 1  # already exists in insights DB
        else:
            created += 1  # would be created

    insights_conn.close()

    return {
        "status":    "dry_run" if dry_run else "ok",
        "processed": processed,
        "created":   created,
        "skipped":   skipped,
        "errors":    errors,
        "dry_run":   dry_run,
    }


def _maybe_write_si_card(insight: XInsight) -> None:
    """Write a self-improvement card stub for a new insight."""
    if not _SI_INBOX.is_dir():
        return
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    safe_id = re.sub(r"[^a-zA-Z0-9-]", "-", insight.x_item_id)[-24:]
    card_path = _SI_INBOX / f"{ts}-x-insight-{safe_id}.md"
    if card_path.exists():
        return
    kp_block = (
        "\n".join(f"- {p}" for p in insight.key_points)
        if insight.key_points
        else "- (see source)"
    )
    body = (
        f"# X Insight: {insight.topic} / {insight.insight_type}\n\n"
        f"**Summary:** {insight.summary}\n\n"
        f"**Key points:**\n{kp_block}\n\n"
        f"**Relevance score:** {insight.relevance_score:.2f}\n"
        f"**Source:** {insight.source_url or '(no URL)'}\n"
        f"**Author:** @{insight.author_handle or 'unknown'}\n\n"
        f"*Auto-generated by x_api insight_pipeline. Review and categorise.*\n"
    )
    try:
        card_path.write_text(body, encoding="utf-8")
    except OSError:
        pass


