context-preprocessor:
  build:
    context: ./context-preprocessor
  container_name: context-preprocessor
  restart: unless-stopped
  ports:
    - "0.0.0.0:8028:8028"
  environment:
    - TZ=America/Denver
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "5"
