#!/usr/bin/env node
/**
 * scripts/daily_summary.js — Nightly call-log digest
 *
 * Queries yesterday's calls from SQLite, formats a concise HTML email,
 * and sends it via SendGrid.
 *
 * Run via cron (e.g. daily at 6:30 AM MT):
 *   30 12 * * * cd /app && node scripts/daily_summary.js >> /var/log/bob-summary.log 2>&1
 */

'use strict';

require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });

const sgMail    = require('@sendgrid/mail');
const callLogger = require('../call_logger');

sgMail.setApiKey(process.env.SENDGRID_API_KEY);

const RECIPIENT = process.env.SUMMARY_EMAIL || 'mearley@symphonysmarthomes.com';
const SENDER    = 'bob@symphonysmarthomes.com';

// ─── Helpers ──────────────────────────────────────────────────────────────────

function yesterday() {
  const d = new Date();
  d.setUTCDate(d.getUTCDate() - 1);
  return d.toISOString().slice(0, 10); // YYYY-MM-DD
}

function formatDuration(secs) {
  if (!secs) return '—';
  const m = Math.floor(secs / 60);
  const s = secs % 60;
  return `${m}m ${s}s`;
}

function buildHtml(date, calls) {
  const rows = calls.map((c, i) => `
    <tr style="background:${i % 2 === 0 ? '#f9f9f9' : '#fff'}">
      <td>${new Date(c.started_at).toLocaleTimeString('en-US', { timeZone: 'America/Denver' })}</td>
      <td>${c.caller_number || '—'}</td>
      <td>${c.client_id ? `Client #${c.client_id}` : 'Unknown'}</td>
      <td>${formatDuration(c.duration_s)}</td>
      <td>${c.outcome || '—'}</td>
      <td>${c.transcript_summary || '—'}</td>
    </tr>`).join('');

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Bob Daily Summary — ${date}</title></head>
<body style="font-family:Arial,sans-serif;max-width:900px;margin:auto;padding:20px">
  <h2 style="color:#1a2e4a">📞 Bob Call Summary — ${date}</h2>
  <p><strong>${calls.length}</strong> call(s) handled on ${date}.</p>
  <table border="0" cellspacing="0" cellpadding="8" width="100%"
         style="border-collapse:collapse;font-size:13px">
    <thead>
      <tr style="background:#1a2e4a;color:#fff">
        <th align="left">Time (MT)</th>
        <th align="left">Caller</th>
        <th align="left">Client</th>
        <th align="left">Duration</th>
        <th align="left">Outcome</th>
        <th align="left">Summary</th>
      </tr>
    </thead>
    <tbody>${rows || '<tr><td colspan="6">No calls recorded.</td></tr>'}</tbody>
  </table>
  <p style="color:#888;font-size:11px;margin-top:20px">Generated by Bob the Conductor · Symphony Smart Homes</p>
</body>
</html>`;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

(async () => {
  const date  = yesterday();
  const calls = callLogger.getCallsByDate(date);

  console.log(`[daily_summary] ${date}: ${calls.length} call(s)`);

  const html = buildHtml(date, calls);

  await sgMail.send({
    to:      RECIPIENT,
    from:    SENDER,
    subject: `Bob Daily Summary — ${date} (${calls.length} calls)`,
    html,
  });

  console.log(`[daily_summary] Email sent to ${RECIPIENT}`);
})();
