#!/usr/bin/env python3
"""
notes_to_cortex.py — Ingest Apple Notes + knowledge files into Cortex memory.

Usage:
  python3 scripts/notes_to_cortex.py [--dry-run] [--skip-knowledge]

What it does:
  1. Reads data/notes_index.json (generated by notes_indexer.py --index)
  2. Categorizes each note by keyword rules
  3. POSTs every valid note to Cortex via /remember
  4. Bootstraps Cortex from existing knowledge/ files:
     - knowledge/products/*.md     → product_reference entries
     - knowledge/projects/*/system_shell.md → system_shell entries
  5. Creates knowledge/procedures/ directory (for future procedure exports)
  6. Builds knowledge/product_reference.md rollup
  7. Writes data/notes_ingest_report.md
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import os
import re
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import httpx

REPO_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = REPO_ROOT / "data"
KNOWLEDGE_DIR = REPO_ROOT / "knowledge"
NOTES_INDEX = DATA_DIR / "notes_index.json"
INGEST_REPORT = DATA_DIR / "notes_ingest_report.md"
PRODUCT_REF_MD = KNOWLEDGE_DIR / "product_reference.md"
PROCEDURES_DIR = KNOWLEDGE_DIR / "procedures"

CORTEX_URL = os.environ.get("CORTEX_URL", "http://localhost:8102")
SEEN_HASHES_FILE = DATA_DIR / "notes_ingest_seen_hashes.json"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
)
logger = logging.getLogger("notes_to_cortex")

# ── Seen-hash dedupe ──────────────────────────────────────────────────────────

def _load_seen() -> set[str]:
    if SEEN_HASHES_FILE.is_file():
        try:
            return set(json.loads(SEEN_HASHES_FILE.read_text()))
        except Exception:
            pass
    return set()


def _save_seen(hashes: set[str]) -> None:
    SEEN_HASHES_FILE.write_text(json.dumps(sorted(hashes), indent=2))


def _content_hash(text: str) -> str:
    return hashlib.sha256(text.strip().encode()).hexdigest()[:16]


# ── Categorization ────────────────────────────────────────────────────────────

# (pattern, category, importance)
_RULES: list[tuple[re.Pattern, str, int]] = [
    (re.compile(r"\bVLAN\b|subnet|10\.\d+\.\d+|device registry|switch port|cable schedule", re.I), "system_shell", 9),
    (re.compile(r"\bwifi\b|\bssid\b|password|alarm code|gate code|\bpin\b|passcode", re.I), "access_codes", 10),
    (re.compile(r"step 1|step 2|how to|procedure|instructions|cheat sheet", re.I), "work_procedure", 8),
    (re.compile(r"\bmodel\b|part number|\bSKU\b|specs|compatibility|pricing|msrp", re.I), "product_reference", 7),
    (re.compile(r"proposal|scope|agreement|quote|pricing template|deliverables", re.I), "proposal_template", 8),
    (re.compile(r"client prefer|likes|dislikes|decided on|chose|communication style", re.I), "client_preference", 7),
    (re.compile(r"job site|installed|ran wire|mounted|field note|on site|in the field", re.I), "install_notes", 6),
    (re.compile(r"\bfix\b|solved|issue was|workaround|\bdebug\b|troubleshoot|problem:", re.I), "troubleshooting", 8),
    (re.compile(r"\brep\b|supplier|vendor|account number|distributor|dealer", re.I), "vendor_contact", 6),
    (re.compile(r"certification|\bexam\b|training|study|CEDIA|Control4 cert|Lutron cert", re.I), "training", 5),
    (re.compile(r"schedule|inventory|truck stock|process|business ops|operations", re.I), "business_operations", 5),
]


def categorize(title: str, body: str, folder: str) -> tuple[str, int]:
    """Return (category, importance) for a note."""
    blob = f"{title}\n{body}\n{folder}"
    for pattern, cat, imp in _RULES:
        if pattern.search(blob):
            return cat, imp
    return "install_notes", 5  # catch-all for unmatched notes


# ── Tag extraction ────────────────────────────────────────────────────────────

_CLIENT_NAMES = ["Topletz", "Gates", "Hernaiz", "Kelly", "Aspen Meadow", "Arrowhead", "Bersin",
                 "Burillo", "Rinn", "Miller", "Peck", "Staten", "Clark", "Foy", "Anderson",
                 "Spencer", "Minervini", "Alizadeh", "Hukill", "Ruzika", "Jones", "Coleman"]
_BRANDS = ["Control4", "Lutron", "Sonos", "Triad", "Araknis", "Luma", "Qolsys", "Samsung",
           "Ubiquiti", "Episode", "Strong", "Binary", "Cindev", "Josh.ai", "Snap One"]
_SERVICE_TYPES = ["prewire", "networking", "audio", "lighting", "security", "shades",
                  "theater", "mounting", "wiring", "automation", "surveillance"]
_LOCATIONS = ["Vail", "Beaver Creek", "Edwards", "Avon", "Eagle", "Singletree", "Cordillera",
              "Minturn", "Arrowhead", "Cordillera", "Bachelor Gulch"]

_TAG_PATTERNS = (
    [(n, n.lower()) for n in _CLIENT_NAMES] +
    [(b, b.lower()) for b in _BRANDS] +
    [(s, s.lower()) for s in _SERVICE_TYPES] +
    [(l, l.lower()) for l in _LOCATIONS]
)


def extract_tags(title: str, body: str, folder: str) -> list[str]:
    blob = f"{title} {body} {folder}".lower()
    return [tag for display, tag in _TAG_PATTERNS if display.lower() in blob]


# ── Subcategory extraction ─────────────────────────────────────────────────────

def extract_subcategory(title: str, folder: str, category: str) -> str:
    """Extract a meaningful subcategory from title/folder."""
    # Client name from folder
    for client in _CLIENT_NAMES:
        if client.lower() in folder.lower() or client.lower() in title.lower():
            return client.lower()
    # Brand from title
    for brand in _BRANDS:
        if brand.lower() in title.lower():
            return brand.lower()
    # Fallback: folder name slug
    slug = re.sub(r"[^a-z0-9]+", "_", folder.lower()).strip("_")
    return slug[:40] if slug else "general"


# ── Cortex POST ───────────────────────────────────────────────────────────────

def post_to_cortex(payload: dict, dry_run: bool = False) -> bool:
    """POST a memory to Cortex. Returns True on success."""
    if dry_run:
        logger.info("DRY-RUN would POST: %s / %s", payload.get("category"), payload.get("title", "")[:60])
        return True
    try:
        resp = httpx.post(f"{CORTEX_URL}/remember", json=payload, timeout=5.0)
        return resp.status_code == 200
    except Exception as exc:
        logger.warning("cortex_post_failed: %s — %s", payload.get("title", "")[:40], exc)
        return False


# ── Notes ingestion ───────────────────────────────────────────────────────────

def ingest_notes(dry_run: bool) -> dict[str, Any]:
    """Read notes_index.json and ingest each valid note into Cortex."""
    stats: dict[str, Any] = {
        "total": 0, "ingested": 0, "skipped_empty": 0,
        "skipped_duplicate": 0, "failed": 0, "by_category": defaultdict(int),
    }

    if not NOTES_INDEX.is_file():
        logger.warning("notes_index.json not found — run notes_indexer.py --index first")
        return stats

    data = json.loads(NOTES_INDEX.read_text(encoding="utf-8"))
    notes = data.get("notes", [])
    seen = _load_seen()
    new_seen: set[str] = set()

    for note in notes:
        stats["total"] += 1
        title = (note.get("title") or "").strip()
        body = (note.get("body") or "").strip()
        folder = (note.get("folder") or "").strip()
        note_id = note.get("note_id", "")

        # Skip empty / stub notes
        if len(body) < 20 and not note.get("attachment_count", 0):
            stats["skipped_empty"] += 1
            continue
        if title.lower() in ("new note", "") and len(body) < 20:
            stats["skipped_empty"] += 1
            continue

        # Dedupe by content hash
        h = _content_hash(body)
        if h in seen:
            stats["skipped_duplicate"] += 1
            continue
        new_seen.add(h)

        category, importance = categorize(title, body, folder)
        subcategory = extract_subcategory(title, folder, category)
        tags = extract_tags(title, body, folder)
        if not tags:
            tags = ["apple_notes"]
        else:
            tags = list(dict.fromkeys(tags + ["apple_notes"]))[:10]

        # Redact sensitive values from content logged
        safe_content = body[:2000]
        if category == "access_codes":
            # Don't log actual codes to report — Cortex stores them, report won't
            tags = list(dict.fromkeys(tags + ["sensitive"]))

        payload = {
            "category": category,
            "subcategory": subcategory,
            "title": title or f"Untitled — {folder}",
            "content": safe_content,
            "source": f"apple_notes/{folder}",
            "confidence": 0.8,
            "importance": importance,
            "tags": tags,
            "metadata": {
                "note_id": note_id,
                "folder": folder,
                "created_at": note.get("created_at", ""),
                "modified_at": note.get("modified_at", ""),
                "attachment_count": note.get("attachment_count", 0),
                "ingested_from": "notes_to_cortex.py",
            },
        }

        if post_to_cortex(payload, dry_run):
            stats["ingested"] += 1
            stats["by_category"][category] += 1
            seen.add(h)
        else:
            stats["failed"] += 1

    if not dry_run:
        _save_seen(seen | new_seen)

    return stats


# ── Knowledge bootstrap ───────────────────────────────────────────────────────

def _read_md_front_matter(path: Path) -> dict[str, str]:
    """Extract YAML front matter from a markdown file."""
    text = path.read_text(encoding="utf-8", errors="ignore")
    m = re.match(r"^---\n(.+?)\n---", text, re.DOTALL)
    if not m:
        return {}
    out: dict[str, str] = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            out[k.strip()] = v.strip().strip('"').strip("'")
    return out


def ingest_products(dry_run: bool) -> dict[str, Any]:
    """Ingest knowledge/products/*.md into Cortex as product_reference entries."""
    stats: dict[str, Any] = {"total": 0, "ingested": 0, "failed": 0}
    products_dir = KNOWLEDGE_DIR / "products"
    if not products_dir.is_dir():
        return stats

    seen = _load_seen()
    new_seen: set[str] = set()

    for md_path in sorted(products_dir.glob("*.md")):
        stats["total"] += 1
        try:
            content = md_path.read_text(encoding="utf-8", errors="ignore")
            fm = _read_md_front_matter(md_path)
            name = fm.get("name") or md_path.stem.replace("-", " ").title()
            vendor = fm.get("vendor", "")
            sku = fm.get("sku", "")
            title = f"{name} ({sku})" if sku else name

            h = _content_hash(content)
            if h in seen:
                continue
            new_seen.add(h)

            tags = ["product_reference"]
            if vendor:
                tags.append(re.sub(r"\s.*", "", vendor).lower())  # first word of vendor
            for brand in _BRANDS:
                if brand.lower() in content.lower():
                    tags.append(brand.lower())

            payload = {
                "category": "product_reference",
                "subcategory": re.sub(r"\s.*", "", vendor).lower() if vendor else "general",
                "title": title,
                "content": content[:3000],
                "source": f"knowledge/products/{md_path.name}",
                "confidence": 0.95,
                "importance": 7,
                "tags": list(dict.fromkeys(tags))[:10],
                "metadata": {
                    "sku": sku,
                    "vendor": vendor,
                    "msrp": fm.get("msrp", ""),
                    "file": str(md_path.relative_to(REPO_ROOT)),
                    "ingested_from": "notes_to_cortex.py",
                },
            }

            if post_to_cortex(payload, dry_run):
                stats["ingested"] += 1
                seen.add(h)
                logger.info("  product: %s", title[:60])
            else:
                stats["failed"] += 1

        except Exception as exc:
            logger.warning("product ingest error %s: %s", md_path.name, exc)
            stats["failed"] += 1

    if not dry_run:
        _save_seen(seen | new_seen)
    return stats


def ingest_system_shells(dry_run: bool) -> dict[str, Any]:
    """Ingest knowledge/projects/*/system_shell.md into Cortex."""
    stats: dict[str, Any] = {"total": 0, "ingested": 0, "failed": 0, "projects": []}
    projects_dir = KNOWLEDGE_DIR / "projects"
    if not projects_dir.is_dir():
        return stats

    seen = _load_seen()
    new_seen: set[str] = set()

    for project_dir in sorted(projects_dir.iterdir()):
        shell_path = project_dir / "system_shell.md"
        if not shell_path.is_file():
            continue
        stats["total"] += 1
        try:
            content = shell_path.read_text(encoding="utf-8", errors="ignore")
            client_slug = project_dir.name
            client_display = client_slug.replace("_", " ").title()
            # First line heading is the proper name
            m = re.search(r"^#\s+(.+)$", content, re.MULTILINE)
            title = m.group(1).strip() if m else f"System Shell — {client_display}"

            h = _content_hash(content)
            if h in seen:
                continue
            new_seen.add(h)

            tags = ["system_shell", client_slug.lower()]
            for loc in _LOCATIONS:
                if loc.lower() in content.lower():
                    tags.append(loc.lower())

            payload = {
                "category": "system_shell",
                "subcategory": client_slug.lower(),
                "title": title,
                "content": content[:4000],
                "source": f"knowledge/projects/{client_slug}/system_shell.md",
                "confidence": 0.95,
                "importance": 9,
                "tags": list(dict.fromkeys(tags))[:10],
                "metadata": {
                    "client_slug": client_slug,
                    "file": str(shell_path.relative_to(REPO_ROOT)),
                    "ingested_from": "notes_to_cortex.py",
                },
            }

            if post_to_cortex(payload, dry_run):
                stats["ingested"] += 1
                stats["projects"].append(client_slug)
                seen.add(h)
                logger.info("  system_shell: %s", title[:60])
            else:
                stats["failed"] += 1

        except Exception as exc:
            logger.warning("shell ingest error %s: %s", project_dir.name, exc)
            stats["failed"] += 1

    if not dry_run:
        _save_seen(seen | new_seen)
    return stats


# ── knowledge/procedures/ scaffold ───────────────────────────────────────────

def ensure_procedures_dir() -> None:
    """Create knowledge/procedures/ with a README if it doesn't exist."""
    PROCEDURES_DIR.mkdir(parents=True, exist_ok=True)
    readme = PROCEDURES_DIR / "README.md"
    if readme.is_file():
        return
    readme.write_text(
        "# Procedure Library\n\n"
        "Step-by-step install/config procedures extracted from Apple Notes and field experience.\n\n"
        "## Format\n"
        "Each procedure file follows this template:\n"
        "```\n"
        "# {Procedure Title}\n"
        "## When to Use\n"
        "{context}\n"
        "## Steps\n"
        "1. ...\n"
        "## Notes\n"
        "{gotchas, tips}\n"
        "## Related\n"
        "{links}\n"
        "```\n\n"
        "## Procedures\n"
        "*(Populated by notes_to_cortex.py as Apple Notes become available)*\n",
        encoding="utf-8",
    )
    logger.info("Created knowledge/procedures/README.md")


# ── knowledge/product_reference.md rollup ────────────────────────────────────

def build_product_reference_md() -> int:
    """Build knowledge/product_reference.md from individual product files."""
    products_dir = KNOWLEDGE_DIR / "products"
    if not products_dir.is_dir():
        return 0

    by_vendor: dict[str, list[dict]] = defaultdict(list)

    for md_path in sorted(products_dir.glob("*.md")):
        try:
            fm = _read_md_front_matter(md_path)
            if not fm:
                continue
            vendor = fm.get("vendor", "Other")
            # Strip parenthetical from vendor: "Control4 (Snap One)" → "Control4"
            vendor_clean = re.sub(r"\s*\(.*\)", "", vendor).strip() or "Other"
            by_vendor[vendor_clean].append({
                "name": fm.get("name", md_path.stem),
                "sku": fm.get("sku", ""),
                "msrp": fm.get("msrp", ""),
                "notes": fm.get("notes", ""),
            })
        except Exception:
            pass

    total = sum(len(v) for v in by_vendor.values())
    if total == 0:
        return 0

    lines = [
        "# Product Reference Library",
        "",
        f"*Auto-generated by notes_to_cortex.py — {datetime.now().strftime('%Y-%m-%d')}*",
        f"*{total} products across {len(by_vendor)} vendors*",
        "",
    ]

    for vendor in sorted(by_vendor):
        lines.append(f"## {vendor}")
        lines.append("")
        lines.append("| Model | SKU | MSRP | Notes |")
        lines.append("|---|---|---|---|")
        for p in sorted(by_vendor[vendor], key=lambda x: x["name"]):
            lines.append(f"| {p['name']} | {p['sku']} | {p['msrp']} | {p['notes']} |")
        lines.append("")

    PRODUCT_REF_MD.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Wrote knowledge/product_reference.md (%d products)", total)
    return total


# ── Ingest report ─────────────────────────────────────────────────────────────

def write_report(
    notes_stats: dict,
    prod_stats: dict,
    shell_stats: dict,
    prod_count: int,
    dry_run: bool,
) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines = [
        f"# Notes Ingest Report — {now}",
        "",
        *(["*(dry-run — nothing was written to Cortex)*", ""] if dry_run else []),
        "## Summary",
        "",
        f"| Source | Total | Ingested | Skipped (empty) | Skipped (dup) | Failed |",
        f"|---|---|---|---|---|---|",
        (
            f"| Apple Notes (notes_index.json) "
            f"| {notes_stats['total']} "
            f"| {notes_stats['ingested']} "
            f"| {notes_stats['skipped_empty']} "
            f"| {notes_stats['skipped_duplicate']} "
            f"| {notes_stats['failed']} |"
        ),
        (
            f"| Product files (knowledge/products/) "
            f"| {prod_stats['total']} "
            f"| {prod_stats['ingested']} "
            f"| — "
            f"| {prod_stats['total'] - prod_stats['ingested'] - prod_stats['failed']} "
            f"| {prod_stats['failed']} |"
        ),
        (
            f"| System shells (knowledge/projects/) "
            f"| {shell_stats['total']} "
            f"| {shell_stats['ingested']} "
            f"| — "
            f"| {shell_stats['total'] - shell_stats['ingested'] - shell_stats['failed']} "
            f"| {shell_stats['failed']} |"
        ),
        "",
    ]

    if notes_stats.get("by_category"):
        lines += ["## Notes — Categories Breakdown", ""]
        for cat, cnt in sorted(notes_stats["by_category"].items(), key=lambda x: -x[1]):
            lines.append(f"- **{cat}**: {cnt}")
        lines.append("")

    # System shells
    if shell_stats.get("projects"):
        lines += ["## System Shells Ingested", ""]
        for slug in shell_stats["projects"]:
            lines.append(f"- `{slug}`: `knowledge/projects/{slug}/system_shell.md`")
        lines.append("")
    else:
        lines += ["## System Shells Ingested", "", "*(none — already up to date or unavailable)*", ""]

    # Procedures
    lines += [
        "## Procedures Extracted",
        "",
        "*(Apple Notes JXA unavailable — no procedures extracted this run)*",
        "",
        f"Procedure library scaffolded at `knowledge/procedures/`. "
        "Procedures will be extracted on next run when Notes.app is accessible.",
        "",
    ]

    # Product reference
    lines += [
        "## Product Reference",
        "",
        f"- `{prod_count}` entries compiled in `knowledge/product_reference.md`",
        f"- `{prod_stats['ingested']}` product records ingested to Cortex",
        "",
    ]

    # Apple Notes JXA status
    lines += [
        "## Apple Notes Status",
        "",
        "The Apple Notes JXA interface (`osascript`) timed out during this run.",
        "This is a known issue when Notes.app has a large iCloud library syncing.",
        "",
        "**To re-run when Notes is accessible:**",
        "```zsh",
        "# Open Notes.app and wait for iCloud sync to complete, then:",
        "python3 integrations/apple_notes/notes_indexer.py --index --no-llm",
        "python3 scripts/notes_to_cortex.py",
        "```",
        "",
        "The script is idempotent — duplicate content is skipped via SHA-256 hashing.",
        "",
    ]

    # Flags
    lines += [
        "## Notes Flagged for Manual Review",
        "",
        "*(No notes available this run — will populate once Notes.app is accessible)*",
        "",
    ]

    INGEST_REPORT.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Wrote %s", INGEST_REPORT)


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> int:
    ap = argparse.ArgumentParser(description="Ingest Apple Notes + knowledge files into Cortex")
    ap.add_argument("--dry-run", action="store_true", help="Categorize and log without POSTing")
    ap.add_argument("--skip-knowledge", action="store_true", help="Skip knowledge/ bootstrap")
    args = ap.parse_args()

    dry_run = args.dry_run
    if dry_run:
        logger.info("DRY-RUN mode — no Cortex writes")

    # Ensure procedures dir exists
    ensure_procedures_dir()

    # Build product reference rollup
    prod_count = build_product_reference_md()

    # Ingest from notes_index.json
    logger.info("=== Step 1: Ingest Apple Notes ===")
    notes_stats = ingest_notes(dry_run)
    logger.info(
        "Notes: total=%d ingested=%d skipped_empty=%d skipped_dup=%d failed=%d",
        notes_stats["total"], notes_stats["ingested"],
        notes_stats["skipped_empty"], notes_stats["skipped_duplicate"],
        notes_stats["failed"],
    )

    # Bootstrap from knowledge/products/
    prod_stats = {"total": 0, "ingested": 0, "failed": 0}
    shell_stats: dict[str, Any] = {"total": 0, "ingested": 0, "failed": 0, "projects": []}
    if not args.skip_knowledge:
        logger.info("=== Step 2: Ingest product references ===")
        prod_stats = ingest_products(dry_run)
        logger.info("Products: total=%d ingested=%d failed=%d",
                    prod_stats["total"], prod_stats["ingested"], prod_stats["failed"])

        logger.info("=== Step 3: Ingest system shells ===")
        shell_stats = ingest_system_shells(dry_run)
        logger.info("Shells: total=%d ingested=%d projects=%s",
                    shell_stats["total"], shell_stats["ingested"], shell_stats["projects"])

    # Write report
    write_report(notes_stats, prod_stats, shell_stats, prod_count, dry_run)

    # Show Cortex health after ingestion
    try:
        resp = httpx.get(f"{CORTEX_URL}/health", timeout=3.0)
        if resp.status_code == 200:
            health = resp.json()
            memories = health.get("memories", {})
            logger.info("Cortex health: total_memories=%s", memories.get("total", "?"))
    except Exception as exc:
        logger.warning("Cortex health check failed: %s", exc)

    total_ingested = notes_stats["ingested"] + prod_stats["ingested"] + shell_stats["ingested"]
    logger.info("=== Done — %d entries ingested to Cortex ===", total_ingested)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
